### ISSUE TITLE
Crash when duplicate items are about to be viewed after library import

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#143]
Exception:

```
System.InvalidOperationException: InvalidOperation_EnumFailedVersion. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485
   at SharedLibrary!<BaseAddress>+0x3be01b
   at System.Collections.Generic.List<System.Object>.Enumerator.MoveNext()
   at BreadPlayer!<BaseAddress>+0xf96832
   at BreadPlayer.ViewModels.SettingsViewModel.<>c__DisplayClass75_0.<DeleteDuplicates>b__0(Models.Mediafile s)
   at SharedLibrary!<BaseAddress>+0x3c2b04
   at BreadPlayer!<BaseAddress>+0xd0eee9
   at BreadPlayer!<BaseAddress>+0x116691f
   at SharedLibrary!<BaseAddress>+0x4511ee
   at SharedLibrary!<BaseAddress>+0x451168
   at SharedLibrary!<BaseAddress>+0x50c81a
   at BreadPlayer!<BaseAddress>+0x1165c19
   at SharedLibrary!<BaseAddress>+0x69993e
   at SharedLibrary!<BaseAddress>+0x497d7c
```

**Comment by cadayton** [comment]
Version 2.2.0.0 still crashing on Windows Phone on start-up. This seems to be happening even prior to the loading of the music library.   Have installed on Windows 10 too no crashes of the app yet.

**Comment by theweavrs** [comment]
Can you please attach the log? It would be in your Music Library under BreadPlayerLogs folder.

**Comment by theweavrs** [comment]
This was fixed.
