### ISSUE TITLE
Crash when adding song to playlist

### ISSUE THREAD

**Issue by CharlieFoxTwo** [theweavrs/BreadPlayer#153]
### Actual Behaviour:
After clicking the (+) sign next to a song and selecting the playlist to add the song to, the app crashes.

### Expected Behaviour:

1.  Create playlist
2.  Add song to playlist
3.  ???
4.  Profit. 

### Steps to reproduce the bug:

1.  Create playlist
2.  Add song to playlist
3.  App crashes (no profit)

### General Information:
1. Bread Player Version: v2.3.0-beta
2. Device Type: PC
3. OS Version: Windows 10 14393.1480

### Additional Comments:
From log file:
18:24:09:730|INFO | 3|XLog.LogManager|>>> LogManager initialized successfully. UTC time: Sat, 22 Jul 2017 01:24:09 GMT
18:24:09:750|INFO | 3|BLogger|Events initialized. Progressing in app constructor.
18:24:09:798|INFO | 3|BLogger|App launched and session started...
18:24:09:748|INFO | 3|BLogger|Logger initialized. Progressing in app constructor.
18:24:09:822|INFO | 3|BLogger|Content set to Window successfully...
18:24:09:822|INFO | 3|BLogger|Navigating to Shell...
18:24:11:149|INFO | 3|BLogger|App left background and is now in foreground...
18:24:12:937|INFO | 8|BLogger|Library successfully loaded!
18:25:52:931|FATAL| 3|BLogger|Something caused the app to crash! --> DBreeze.Exceptions.DBreezeException: Transaction doesn't exist anymore!
   at DBreeze.Transactions.TransactionsCoordinator.GetTable_WRITE(String tableName, Int32 transactionThreadId)
   at DBreeze.Transactions.Transaction.GetWriteTableFromBuffer(String tableName)
   at DBreeze.Transactions.Transaction.Technical_SetTable_OverwriteIsNotAllowed(String tableName)
   at BreadPlayer.Database.KeyValueStoreDatabaseService.<>c__DisplayClass15_0.<InsertRecords>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at BreadPlayer.Database.KeyValueStoreDatabaseService.<InsertRecords>d__15.MoveNext()
   at BreadPlayer.Database.ChildSongsService.<InsertTracksAsync>d__7.MoveNext()
   at BreadPlayer.ViewModels.LibraryViewModel.<>c__DisplayClass130_0.<<AddSongsToPlaylist>b__0>d.MoveNext()
   at BreadPlayer.ViewModels.LibraryViewModel.<AddSongsToPlaylist>d__130.MoveNext()
   at BreadPlayer.ViewModels.LibraryViewModel.<>c__DisplayClass132_0.<<AddPlaylistAsync>b__0>d.MoveNext()
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

**Comment by theweavrs** [comment]
Ha! Good catch. This will have a simple fix. 

Thanks for reporting.
