### ISSUE TITLE
App crash when navigating to NowPlayingView

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#199]
https://sentry.io/abdullah-atta/breadplayer/issues/395672867/

```
Message: Something caused the app to crash! 

Exception:System.Reflection.TargetInvocationException: Arg_TargetInvocationException ---> System.Exception: The application called an interface that was marshalled for a different thread. (Excep_FromHResult 0x8001010E)
   at SharedLibrary!<BaseAddress>+0x553e0f
   at BreadPlayer!<BaseAddress>+0x1adfe05
   at BreadPlayer.Shell.HandleNavigationMessage(Messengers.Message message)
   at SharedLibrary!<BaseAddress>+0x2ebf67
   at SharedLibrary!<BaseAddress>+0x4023fb
   at SharedLibrary!<BaseAddress>+0x3ab73b
   Exception_EndOfInnerExceptionStack
   at SharedLibrary!<BaseAddress>+0x3ab889
   at System.Delegate.DynamicInvoke(Object[] args)
   at BreadPlayer.Messengers.Messenger.Invoke(Messengers.Message message, Delegate method)
   at BreadPlayer.Messengers.Messenger.NotifyColleagues(Messengers.MessageTypes messageType, Object parameter)
   at BreadPlayer.ViewModels.ShellViewModel.NavigateToNowPlayingView(Object para)
   at BreadPlayer!<BaseAddress>+0x1ae95bb
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1ae96d1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x368a33
   at SharedLibrary!<BaseAddress>+0x369031
   at SharedLibrary!<BaseAddress>+0x369b49
   at SharedLibrary!<BaseAddress>+0x369b0f
   at BreadPlayer!<BaseAddress>+0x1aebf17
```

**Comment by theweavrs** [comment]
https://sentry.io/abdullah-atta/breadplayer/issues/395669948/
