### ISSUE TITLE
Startup crash due to an error in InternetConnectivityHelper

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#204]
https://sentry.io/abdullah-atta/breadplayer/issues/403800365/

```
Message: Exception occured in LoadFrame Method. Arguments: {arguments}. 

Exception:System.InvalidOperationException: MoreThanOneMatch
   at BreadPlayer!<BaseAddress>+0x194dee9
   at BreadPlayer.Helpers.InternetConnectivityHelper.RefreshConnection()
   at BreadPlayer.Helpers.InternetConnectivityHelper..ctor()
   at BreadPlayer!<BaseAddress>+0x235a0f3
```

**Comment by theweavrs** [comment]
Fixed in: [commit](https://github.com/theweavrs/BreadPlayer/commit/3e9d4fae0b326ab524abc15f953a44e9bc57241c)
