### ISSUE TITLE
App crash when initializing BreadDispatcher

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#207]
https://sentry.io/abdullah-atta/breadplayer/issues/404208932/

```
Message: Something caused the app to crash! Sender: {sender} 

Exception:System.TypeInitializationException: TypeInitialization_Type_NoTypeAvailable ---> System.Exception: No se ha encontrado el elemento.

No se ha encontrado el elemento.

   at SharedLibrary!<BaseAddress>+0x4a29f0
   at BreadPlayer!<BaseAddress>+0x1f6173e
   at BreadPlayer!<BaseAddress>+0x1f61617
   at BreadPlayer!<BaseAddress>+0x224f5dc
   at BreadPlayer.Dispatcher.BreadDispatcher..cctor()
   at SharedLibrary!<BaseAddress>+0x45c4e0
   Exception_EndOfInnerExceptionStack
   at SharedLibrary!<BaseAddress>+0x45c59c
   at SharedLibrary!<BaseAddress>+0x45c3df
   at BreadPlayer!<BaseAddress>+0x2b756bb
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d7c00
   at SharedLibrary!<BaseAddress>+0x4d7b88
   at SharedLibrary!<BaseAddress>+0x4d7b47
   at SharedLibrary!<BaseAddress>+0x5471bb
   at BreadPlayer!<BaseAddress>+0x1d13bfa
```

**Comment by theweavrs** [comment]
https://sentry.io/abdullah-atta/breadplayer/issues/404135599/

**Comment by theweavrs** [comment]
https://sentry.io/abdullah-atta/breadplayer/issues/404087258/
